### ISSUE TITLE
Speed up hashing functionality

### ISSUE THREAD

**Issue by tonyfischetti** [tonyfischetti/sake#22]
I discovered that the sha1 hashing is the major time-sink. If we can get that faster, sake's speed will improve greatly

**Comment by tonyfischetti** [comment]
While you're at it, profile it.
See this: http://lukauskas.co.uk/articles/2014/02/12/how-to-make-python-faster-without-trying-that-much/

**Comment by kirbyfan64** [comment]
What about using threads to hash multiple files?

On a side note, [this](http://stackoverflow.com/a/11822995/2097780) is MUCH better than cProfile+gprof2dot.

**Comment by tonyfischetti** [comment]
Damn! That looks much easier! I gotta use that instead. Thanks for the tip!

I was actually thinking of rewriting the sha1 hash implementation but using threads or different processes is a much better idea! If all the files are thrown into a list we could use multiprocessing.Pool to get the concurrent shall hashing virtually for free.

**Comment by tonyfischetti** [comment]
Done as of ef8681c97083ae2bca55c4645fecdd323976ee4d
