### ISSUE TITLE
Possible bugs/oddities with includes and macros

### ISSUE THREAD

**Issue by kirbyfan64** [tonyfischetti/sake#39]
I found the following oddities/inconsistencies with certain things. They may/may not be bugs.

1. Includes are ALWAYS relative to the root directory. In this file structure:

```
x/
 inc.yaml
 Sakefile
 y/
  inc.yaml
  Sakefile
```

Assuming the following file contents:

x/Sakefile:

```yaml
#< inc.yaml
#< y/Sakefile
```

x/y/Sakefile:

```yaml
#< inc.yaml

something:
 help: blah
 formula: echo $CC
```

x/inc.yaml:

```yaml
#! CC=gcc
```

x/y/inc.yaml:

```yaml
#! CC=clang
```

running target `something` will echo gcc, NOT clang. As stated above, includes are always relative to the parent directory. This is how several build systems (aka GNU make) work, but some of those (again GNU make) are not the best role models!

However, if includes are relative to the file's directory (so x/y/Sakefile's include will reference x/y/inc.yaml), it still will cause confusion because people might think that, since includes are relative, so are dependencies...but those are always relative to the parent directory.

Also, relative includes would bite when a config.yaml needs to be included by a file 10 directories down.

So...should includes be relative to the root or the current sakefile? Regardless of the choice, this is likely a gotcha that should be in the docs.

- Empty macros aren't allowed. This:

```yaml
#! M=
```

is rejected by Sake:

```
Failed to parse macro #! M=
```

*Should* they be allowed, though? It would come in handy for things such as file extensions; a configure script could write `#! APPEXT=` on Posix and `#! APPEXT=.exe` on Windows.

- Invalid macros are silently ignored. This has already bitten me several times. This Sakefile:

```yaml
MY_COMPILER=gcc

target:
 help: asdasdasdasdxas
 formula: $MY_COMILER -c x.c -o x.o
```

will have different behavior on Posix and Windows. Since Sake ignores nonexistent macro names, the `$MY_COMILER` will be passed to the shell, invoking system-specific behavior.

Under Posix, this will say that `-c` is not a valid program because `$MY_COMILER`, since it is undefined, will silently be removed...unless it IS defined, in which case no one might notice until the file is tried on Windows.

Speaking of Windows, the command prompt will happily try to find a program named `$MY_COMILER` and fail with the classic `is not an internal or external command, operable program, or batch file`. Ouch.

Also, this is one of the biggest complaints about make. Fixing it wouldn't be difficult; it would amount to changing the `safe_substitute` call to `substitute` and catches errors.

Thoughts?

**Comment by tonyfischetti** [comment]
Good catches!
- includes should remain relative to the root directory. I agree that this is a 'gotcha'; I'll reflect this in the docs
- you've convinced me that blank macros should be allowed. This should be a simple regex change, right? I'll create an issue
- Yeah, perhaps it is better to disallow safe_substitute–I'll make an issue for this.

Do you want to take these issues?

**Comment by kirbyfan64** [comment]
I'll take care of it!

**Comment by tonyfischetti** [comment]
You're awesome!
