### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by tonyfischetti** [tonyfischetti/sake#43]
To replicate, clone commit 183282dfa98cd7f2cc342989b4a03eb6ab47f866 and "sake" the documentation. Why does this happen?

**Comment by kirbyfan64** [comment]
Is this the "Couldn't get a file descriptor" thing?

**Comment by tonyfischetti** [comment]
Oh, I use "open" because it'll open the pdf on my mac.
The error looked something like
`
in_mem_shas['files']....
KeyError: 'files'
`
It was because the 'files' key was missing from in_mem_shas in the cases where in_mem_shas was emptied (like if there is no .shastore–like when it is first cloned). You couldn't replicate this?

Anyway, I fixed it

**Comment by kirbyfan64** [comment]
No, but I know that open on Ubuntu does nothing like the Mac command does!
