### ISSUE TITLE
Support alternative shells

### ISSUE THREAD

**Issue by fiatjaf** [tonyfischetti/sake#58]
Currently sake runs the formulas with `/bin/sh`, as this is the shell that `Popen` calls.
However, if passed the argument `executable`, `Popen` would run with any user specified shell.

For example, with the fish shell:

```python
Popen(commands, shell=True, executable='/usr/bin/fish')
```

**Comment by tonyfischetti** [comment]
That's a great idea. I'll work this into the v1.0 release. Feel free to send a pull request if you need this sooner. I would implement it as a flag command line arg to sake like...
```
sake -e /usr/bin/fish
```

**Comment by fiatjaf** [comment]
I am against implementing it as a command line argument. If I'm going to write my scripts inside the Sakefile in the __fish__ language, I should specify the shell for sake to use inside the Sakefile also. A Sakefile with __fish__ scripts cannot ever be run with a __bash__ shell and vice-versa.

I think this should be implemented as a global option of the Sakefile.

I tried to read the code and find a place to introduce this change, but I couldn't get confident about the best way to do it (so I spent some time porting my fish scripts to sh so they could work), but I still think it is a valid feature to have.

**Comment by tonyfischetti** [comment]
Your position against implementing it as a command-line argument is compelling. Implementing it as either a global option of the sakefile, or even an attribute of `formula` is probably a better choice. I'll update you when I implement this

**Comment by tonyfischetti** [comment]
Actually, can you run this?
```
echo $SHELL
```
Popen will run the commands through the $SHELL environment variable on POSIX systems. Is your $SHELL fish?

**Comment by fiatjaf** [comment]
```
fiatjaf@spooner ~> echo $SHELL
/usr/bin/fish
```

My shell is fish, but sake is running the scripts with `/bin/sh`.

**Comment by tonyfischetti** [comment]
Hmm, I wonder why. Python professes to use the $SHELL environment variable :(

**Comment by kirbyfan64** [comment]
Actually, it [unconditionally uses `/bin/sh`](https://hg.python.org/cpython/file/2.7/Lib/subprocess.py#l1208).

**Comment by tonyfischetti** [comment]
Ah, too bad. I was looking [at this](http://stackoverflow.com/a/3172488)
What do you think is best @kirbyfan64?

**Comment by kirbyfan64** [comment]
IMO, a `shell` option in the Sakefile rules would be best because the rules likely will heavily depend on the chosen shell.

**Comment by tonyfischetti** [comment]
Ok, at the top level, or under `formula`?

**Comment by kirbyfan64** [comment]
Top level. Putting it under `formula` might complicate Sakefile checking.

Of course, it's still your call. :)

**Comment by tonyfischetti** [comment]
Done
