### ISSUE TITLE
How to pronounce "sake"

### ISSUE THREAD

**Issue by kojiromike** [tonyfischetti/sake#60]
The README doesn't cover this. At first I thought it was a reference to the alcoholic drink from Japan, but after I read what it does I thought maybe it was a reference to [make](http://pubs.opengroup.org/onlinepubs/009695399/utilities/make.html). Is it さけ or sāk?

**Comment by tonyfischetti** [comment]
At first I pronounced it like さけ but sometimes I pronounce it as if it rhymes with make. I knew it would be ambiguous but I originally intended it to be pronounced さけ. Thanks for asking!
