### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by alexreg** [tonyfischetti/sake#63]
I see that Sake is still listed as beta-stage on the website. It looks usable right now however – do you use it for your projects actively?

Moreover, I notice there hasn't been any real update to the project for 7 months. Is it still under active development? Or at least maintenance? Or nothing?

Great project in any case – one of the most sane and usable general-purpose build systems I've seen! 👍🏼

**Comment by tonyfischetti** [comment]
Hi @alexreg!
Good question. I use it for all my applicable personal projects and use it at work (if that counts as "production"). It's quite usable :)
The only thing stopping me from removing the beta label is hitting version 1 (its 0.9.6 right now).
The only thing stopping me from hitting version one is a more robust *unit* test suite (our functional test suite is complete as far as I'm concerned).
I'm also pretty obsessive about finding and removing all bugs before version 1.

After version 1 (which I'm hoping to get to in the next couple of months) I'd imagine that sake will continue to gather a trickle of new features but pretty slowly. It pretty much does everything I want it to do now, anyway.

To answer your question, I haven't forgot about it! I use it all the time so I would probably never leave sake unmaintained :)

**Comment by tonyfischetti** [comment]
Oh, and thanks for the kind words about sake!

**Comment by alexreg** [comment]
Thanks for the update, @tonyfischetti. It’s good to know it’s usable at least (and in a sense, “safe for production”). There’s no better testament than a project author regularly using his own project!
