### ISSUE TITLE
Empty macros don't work (anymore?)

### ISSUE THREAD

**Issue by kirbyfan64** [tonyfischetti/sake#65]
I'm pretty sure this worked at some point:

```yaml
#! MYMACRO=
```

**Comment by tonyfischetti** [comment]
Hmm, let me check when the last commit that worked in was...

**Comment by kirbyfan64** [comment]
Actually, I lied. This apparently never worked. Oops...

**Comment by tonyfischetti** [comment]
Should we allow it?

**Comment by tonyfischetti** [comment]
Empty macros actually worked for me but there's no downside to the slight change in regex
