### ISSUE TITLE
[feature request] Support shell options in `shell:` value

### ISSUE THREAD

**Issue by stephenchu** [tonyfischetti/sake#74]
Usually, I use `shell: bash` in my Sakefile. More often than not, I will start embedding in my `formula` value a `set -euo pipefail` to make my Bash scripts act more "strict" in order to fail fast.

I would like to be able to just do something like this to save myself from typing out the options:

```
shell: bash -euo pipefail
```

Currently, it fails with the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/sake", line 323, in <module>
    dont_update_shas_of=no_sha_update)
  File "/usr/local/lib/python3.6/site-packages/sakelib/build.py", line 576, in build_this_graph
    run_the_target(G, target, settings)
  File "/usr/local/lib/python3.6/site-packages/sakelib/build.py", line 307, in run_the_target
    run_commands(the_formula, settings)
  File "/usr/local/lib/python3.6/site-packages/sakelib/build.py", line 285, in run_commands
    executable=the_shell)
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bash -euo pipefail': 'bash -euo pipefail'
```

**Comment by tonyfischetti** [comment]
On it!

**Comment by tonyfischetti** [comment]
Can you try it now? (make sure you use the version on github as of commit 1e82261)
If you can confirm that it works, I'll increase the version number and put it on PyPI.
Thanks for catching this :)

**Comment by stephenchu** [comment]
It looks great! I just tested it, works exactly like what I wanted.

🙇

**Comment by tonyfischetti** [comment]
I'm glad to hear that!
Thanks for the request :)
I'll close the issue now

**Comment by stephenchu** [comment]
@tonyfischetti I just found out that the pypi `master-sake==1.1` does not have the commit 1e82261 (I untar'ed the package from that page to look). Am I mistaken to think that this feature should exist in 1.1? Or, is there a upcoming 1.2? Thanks!
