### ISSUE TITLE
Relax `help` key requirement in Sakefile

### ISSUE THREAD

**Issue by stephenchu** [tonyfischetti/sake#75]
I find the requirement for each target to contain a `help:` entry to be little too strict. Specifically, if I am already using a key that is extremely well named, I am still required to add a duplicated `help` entry under it:

```
$ cat Sakefile
"do something really important":
  help: "I mean, really really important. What more do you need to know?"
  formula: echo 42
```

... otherwise my Sakefile won't parse:

```
$ sake help
target 'do something really important' is not allowed to be missing a help message
Failed to accept target 'do something really important'

Error: Sakefile isn't written to specification
```

It is effectively causing my Sakefile to bloat. I would love to relax this `help` requirement to become optional.

**Comment by stephenchu** [comment]
@kirbyfan64 Yes, that is my current workaround and grief 😀 . Hence the creation of this issue. I would love to not have to resort this hack.

**Comment by tonyfischetti** [comment]
The problem with that is `sake help` is supposed to be an integral part of the application. What would it say?

**Comment by stephenchu** [comment]
> The problem with that is `sake help` is supposed to be an integral part of the application. What would it say?

One way would be (stealing from Ruby on Rails `rake --tasks`):

In rake:
```
> rake --tasks --all
rake with_help     # Descriptive help here
rake without_help  #
```

In sake:
```
> sake help
You can 'sake' one of the following...

sake with_help     # Descriptive help here
sake without_help  #
```

Although this would break the yaml stdout it currently behaves. Although I can also envision a `sake help --format yaml` to accommodate that need.
