### ISSUE TITLE
how to run multiple targets in a single invocation?

### ISSUE THREAD

**Issue by omnilinguist** [tonyfischetti/sake#76]
Consider the following simplified `Makefile` and `Sakefile` (tangentially, the fact that an empty `help:` clause is needed in each `Sakefile` target despite not providing any information there is an unfortunate result of #75):
```
$ cat Makefile
.PHONY: a
a:
	echo 'a'

.PHONY: b
b:
	echo 'b'

$ cat Sakefile
a:
  help:
  formula: echo 'a'

b:
  help:
  formula: echo 'b'
```

Since in `make` it is possible to run two targets in succession,
```
$ make a
echo 'a'
a
$ make b
echo 'b'
b
$ make a b
echo 'a'
a
echo 'b'
b
```

I would expect that Sake should support something similar. However, that doesn't seem to be the case:
```
$ sake a
Running target a
echo 'a'
a
Done
$ sake b
Running target b
echo 'b'
b
Done
$ sake a b
usage: sake [-h] [-v] [-V] [-q] [-c] [-F] [-r] [-p] [-n] [-E] [-f OUTFILE]
            [-s CUSTOMSAKE] [-D DEFINES]
            [target]
sake: error: unrecognized arguments: b
```

Instead, one has to resort to invocations like `sake a && sake b` or `sake a; sake b` which work.

This seems to be a regression from `make`, unless this is intentional for some reason - but I don't think that would be the case, given that running `sake` without any targets will execute *every* target (which is a superset of all specific task combinations).

From the documentation, I understand there are meta-targets. However, I could see cases where users would want to run arbitrary combinations of tasks without having to codify each and every one of them explicitly in the `Sakefile`.

**Comment by omnilinguist** [comment]
(Tangentially, the fact that an empty `help:` clause is needed in each `Sakefile` target despite not providing any information there is an unfortunate result of #75.)

**Comment by tonyfischetti** [comment]
This is a really good idea. I hadn't considered doing that before. I'll add this :)

**Comment by tonyfischetti** [comment]
Sorry, a lot of things came up. Since I just use `sake a && sake b` and it works ok, I'm gonna close this issue unless someone else wants to take it on
